config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  root to: "static_pages#index"
  get '/home', to: "static_pages#home"
	
  resources :trades, :categories, :products, :reviews, :brands
  
  resources :conversations do
    resources :messages
  end

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }

  # Messages / Conversations
  get 'messages/index', to: 'messages#index'
  get 'conversations', to: 'conversations#messages/index'

  # Products / Inventory / Search
  get '/my-inventory', to: 'inventories#show'
  get '/products-filtered', to: 'products#index_with_filters'

  post '/products-search', to: 'searches#search'

  # Loans
  post '/loans/ask', to: 'loans#ask'
  get '/loans/ask/cancel/:loan_id', to: 'loans#ask_cancel'
  get '/loans/ask/confirm/:loan_id', to: 'loans#ask_confirm'
  get '/loans/ask/refuse/:loan_id', to: 'loans#ask_refuse'

  get '/loans/back/ask/:loan_id', to: 'loans#back_ask'
  get '/loans/back/confirm/:loan_id', to: 'loans#back_confirm'
  get '/loans/back/refuse/:loan_id', to: 'loans#back_refuse'

  # Profile Info / SMS verification
  get '/profile/account', to: 'profile#account'

  get '/profile/requests-pending', to: 'profile#requests_pending'
  get '/profile/requests-current', to: 'profile#requests_current'
  get '/profile/requests-past', to: 'profile#requests_past'

  get '/profile/asks', to: 'profile#asks'
  get '/profile/asks-pending', to: 'profile#asks_pending'
  get '/profile/asks-current', to: 'profile#asks_current'
  get '/profile/asks-past', to: 'profile#asks_past'

  get '/profile/ask_profile_verification', to: 'profile#ask_profile_verification'
  get '/profile/cancel_profile_verification/:request_id', to: 'profile#cancel_profile_verification'

  post '/profile/verify_profile', to: 'profile#verify_profile'
  get '/profile/close', to: 'profile#close'

  #error views 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/address.rb
class Address < ApplicationRecord
	has_one :user
	geocoded_by :full_address

	after_validation :geocode

	# after_initialize do |address|
	# 	a = address.geocode
	# 	puts a
 #  end

	def full_address
		["#{self.street}", self.city, self.country].compact.join(', ')
	end
	
	def to_string
		self.street + ', ' + self.postal_code + ' ' + self.city + ', ' + self.country
	end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # This scope validation takes the sender_id and recipient_id for the conversation and checks whether a conversation exists between the two ids because we only want two users to have one conversation.

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/loan.rb
class Loan < ApplicationRecord
	has_one :product
	has_one :owner, class_name: 'User', foreign_key: 'owner_id', inverse_of: :owns
	has_one :borrower, class_name: 'User', foreign_key: 'borrower_id', inverse_of: :borrows
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :inventory
  has_one :brand
  has_and_belongs_to_many :categories
  has_many :loans
  has_many_attached :uploads

  accepts_nested_attributes_for :brand

  paginates_per 10
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :reviewer, :class_name => 'User', inverse_of: :reviews
	belongs_to :reviewed_user, :class_name => 'User', inverse_of: :notes
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable #added to generate email confirmations after creating account

  belongs_to :address
  accepts_nested_attributes_for :address
  
	has_one_attached :header_image
  has_many :trades
  has_many :owns, inverse_of: :owner, :class_name => 'Loans', :foreign_key => 'owner_id'
  has_many :borrows, inverse_of: :borrower, :class_name => 'Loans', :foreign_key => 'borrower_id'
  has_many :reviews, dependent: :destroy, inverse_of: :reviewer, :class_name => 'Review'
  has_many :notes, dependent: :destroy, inverse_of: :reviewed_user, :class_name => 'Review'

  private
    attr_accessor :verification_code
  public
    def get_verification_code
      @verification_code
    end

    def set_verification_code(code)
      @verification_code = code
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

  def index
    @products = Product.all
    @users = User.all

    sql = "SELECT DISTINCT * from conversations AS c WHERE c.sender_id=#{current_user.id} OR c.recipient_id=#{current_user.id};"
    @conversations = []
    
    ActiveRecord::Base.connection.execute(sql).each do |row|
      @conversations << Conversation.new(row)
    end
  end

  def create
    @product = Product.find(params[:product_id])
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(sender_id: params[:sender_id] ,recipient_id: params[:recipient_id], product: @product)
    end
    redirect_to product_conversation_messages_path(@conversation, @product.id)
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
	attr_accessor :request_params

	def search_params
		@request_params.require(:search).permit(:location, :keyword, categories: [])
	end

	def compute_search_filters
		permited = search_params
		@products_search_params = {}

		if permited[:categories]
			@products_search_params[:categories] = permited[:categories]
		end

		@products_search_params
	end
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/conversations/index.html.erb
<!-- Start Content -->

<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-9 page-content">
        <div class="inner-box">              
          <h2 class="title-2">Boite de réception</h2>
          <div class="table-responsive">
            <div class="table-action">
              <div class="checkbox">
                <label for="checkAll">
                  <input id="checkAll" type="checkbox">
                  Select: All | <a href="#" class="btn btn-xs btn-danger">Delete <i class="fa fa-close"></i></a>
                </label>
              </div>
              <div class="table-search pull-right col-xs-7">
                <div class="form-group">
                  <label class="col-xs-5 control-label text-right">Search <br>
                    <a title="clear filter" class="clear-filter" href="#clear">[clear]</a> 
                  </label>
                  <div class="col-xs-7 searchpan">
                    <input class="form-control" id="filter" type="text">
                  </div>
                </div>
              </div>
            </div>
            
            <table class="table table-striped table-bordered add-manage-table">
              <thead>
                <tr>
                  <th data-type="numeric"></th>
                  <th>Destinataire</th>
                  <th>Date</th>
                </tr>
              </thead>
              <tbody>
                <% @conversations.each do |conversation| %>
                  <tr>
                    <td>
                      <div class="checkbox">
                      <label>
                        <input type="checkbox">
                      </label>
                    </td>
                    <td class="ads-details-td col-xs-12">
                      <% if conversation.sender_id != current_user.id %>
                        <%= link_to "#{User.find(conversation.sender_id).email}", conversation_messages_path(conversation), class: 'inline-block' %>
                      <% else %>
                      <%= link_to "#{User.find(conversation.recipient.id).email}", conversation_messages_path(conversation), class: 'inline-block' %>
                      <% end %>
                    </td>
                    <td>
                      <%= conversation.messages.last.created_at %>
                    </td>
                  </tr>
                  </div>
                <% end %>
              </tbody>
            </table>
          </div>               
        </div>
      </div>
    </div>  
  </div>      
</div>
<!-- End Content -->


<!-- <% @users.each do |user| %>
                     <% if user.id != current_user.id %>
                     <%= link_to "Message #{user.email}", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post", class: 'table table-striped table-bordered add-manage-table' %>
                     <% end %>
                   <% end %> -->