config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  root to: "static_pages#index"
  get '/home', to: "static_pages#home"
	
  resources :trades, :categories, :products, :reviews, :brands
  
  resources :conversations do
    resources :messages
  end

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }

  # Messages / Conversations
  get 'messages/index', to: 'messages#index'
  get 'conversations', to: 'conversations#messages/index'

  # Products / Inventory / Search
  get '/my-inventory', to: 'inventories#show'
  get '/products-filtered', to: 'products#index_with_filters'

  post '/products-search', to: 'searches#search'

  # Loans
  post '/loans/ask', to: 'loans#ask'
  get '/loans/ask/cancel/:loan_id', to: 'loans#ask_cancel'
  get '/loans/ask/confirm/:loan_id', to: 'loans#ask_confirm'
  get '/loans/ask/refuse/:loan_id', to: 'loans#ask_refuse'

  get '/loans/back/ask/:loan_id', to: 'loans#back_ask'
  get '/loans/back/confirm/:loan_id', to: 'loans#back_confirm'
  get '/loans/back/refuse/:loan_id', to: 'loans#back_refuse'

  # Profile Info / SMS verification
  get '/profile/account', to: 'profile#account'

  get '/profile/requests-pending', to: 'profile#requests_pending'
  get '/profile/requests-current', to: 'profile#requests_current'
  get '/profile/requests-past', to: 'profile#requests_past'

  get '/profile/asks', to: 'profile#asks'
  get '/profile/asks-pending', to: 'profile#asks_pending'
  get '/profile/asks-current', to: 'profile#asks_current'
  get '/profile/asks-past', to: 'profile#asks_past'

  get '/profile/ask_profile_verification', to: 'profile#ask_profile_verification'
  get '/profile/cancel_profile_verification/:request_id', to: 'profile#cancel_profile_verification'

  post '/profile/verify_profile', to: 'profile#verify_profile'
  get '/profile/close', to: 'profile#close'

  #error views 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :inventory
  has_one :brand
  has_and_belongs_to_many :categories
  has_many :loans
  has_many_attached :uploads

  accepts_nested_attributes_for :brand

  paginates_per 10
end

app/controllers/products_controller.rb
STATES = [
			"Neuf",
			"Bon état",
			"Abimé"
		]
class ProductsController < ApplicationController
	before_action :product_param, only: ['create', 'update']
	before_action :product_detail_param, only: ['create', 'update']
	before_action :categories_param, only: ['create', 'update']
	before_action :authenticate_user!

	def product_param
		permited = params.require(:product).permit(:title, :short_desc, :long_desc, :state, uploads: [])
		permited[:inventory_id] = Inventory.find_by(user_id: current_user.id).id
		permited
	end

	def product_detail_param
		params.require(:product).permit(:product_detail => [:name])[:product_detail]
	end

	def categories_param
		params.require(:product).permit(categories: [])[:categories]
	end

	def index
		@categories = Category.all
		ids = Product.where(inventory_id: Inventory.find_by(user_id: current_user.id)).pluck('id');

		(ids << Loan.where(borrower_id: current_user.id, back_ask: nil).pluck('product_id')).flatten!

		@products = Product.where.not(id: ids).order(:title).page params[:page]

		@icon_list = ["fa fa-users", "fa fa-film", "fa fa-briefcase", 
  				"fa fa-wrench", "fa fa-cutlery", "fa fa-music"]
	end

	def index_with_filters
		@categories = Category.all

		ids = Product.where(inventory_id: Inventory.find_by(user_id: current_user.id)).pluck('id');

		(ids << Loan.where(borrower_id: current_user.id, back_ask: nil).pluck('product_id')).flatten!

		s = params[:product_id].split(',')
		if !ids.nil?
			if ids.respond_to? :each
				ids.each do |i|
					if s.include?(i)
						s.delete(i)
					end
				end
			end
		end
		@products = Product.where('id IN (?)', s).order(:title).page params[:page]
		
		@icon_list = ["fa fa-users", "fa fa-film", "fa fa-briefcase", 
  				"fa fa-wrench", "fa fa-cutlery", "fa fa-music"]

		render "index"
	end

	def new
		@brands = Brand.all.order(:name)
		@states = STATES
		@categories = Category.all
		@product = Product.new

	end

	def create
		@p = product_param
		@d = product_detail_param
		@c = categories_param

		@product = Product.create(@p)
		Brand.create(@d)

		if !@c.nil? 
			@c.each do |c|
				c = c.to_i
				unless c <= 0
					@product.categories << Category.find(c)
				end
			end
		end

		redirect_to '/my-inventory'
	end

	def edit
		@brands = Brand.all
		@states = STATES
		
		@product = Product.find(params[:id])
		@categories = []
	 	@product.categories.each { |c|
	 		@categories << c
	 	}

	 	@categories
	end

	def update
		@p = product_param
		@d = product_detail_param
		@c = categories_param

		@product = Product.update(product_param)
		@categories = categories_param

		@categories.each do |c|
			c = c.to_i
			unless c <= 0
				@product.categories << Category.find(c)
			end
		end
		
		redirect_to '/my-inventory'
	end

	def show
		@product = Product.find(params[:id])
		@inventory = Inventory.find(@product.inventory_id)
		@user = User.find(@inventory.user_id)
		@users = User.all
		@conversations = Conversation.all

		@review = Review.new
		@loan = Loan.new
	end

	def destroy
		@id_product = params[:id]
		Product.find(@id_product).destroy

		respond_to do |format|
			format.html
			format.js
		end
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/destroy.js.erb
$('#my-product-<%= @id_product %>').remove()

app/views/products/edit.html.erb
<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <div class="box">
          <h2 class="title-2">Share a new product to the community</h2>
          <div class="row search-bar mb30 red-bg">
            <div class="advanced-search">
              <%= form_for @product, class: "search-form" do |f| %>
                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        Category
                      </span>
                      
                      <%= f.collection_select(:categories, @categories, :id, :name, {}, :multiple => true, class: "dropdown-product selectpicker") %>
                    </label>
                  </div>
                </div>

                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        State
                      </span>
                      <select class="dropdown-product selectpicker" name="product[state]">
                        <% @states.each do |state| %>
                          <option value="<%= state %>"> <%= state %> </option>
                        <% end %>
                      </select>
                    </label>
                  </div>
                </div>

                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        Brand
                      </span>
                      <%= f.fields_for :product_detail do |form| %>
                        <select id="brand-select"class="dropdown-product selectpicker" name="product[product_detail][name]">
                          <option value="new" > Ajouter une marque  </option>
                          <% @brands.each do |brand| %>
                            <% if @product.brand_id == brand.id %>
                              <option selected value="<%= brand %>"> <%= brand.name %> </option>
                            <% else %>
                              <option value="<%= brand %>"> <%= brand.name %> </option>
                            <% end %>
                          <% end %>
                        </select>
                      <% end %>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <div id="brand_field" class="input-icon">
              <input placeholder="Créer une nouvelle marque"type="text" class="form-control input-md" id="custom-brand" />
            </div>

            <div class="form-group mb30">
              <%= f.label :title, class: "control-label" %>
              <%= f.text_field :title, class: 'form-control input-md' %>
            </div>
            <div class="form-group mb30">
              <%= f.label :short_desc, class: "control-label" %>
              <%= f.text_area :short_desc, class: 'form-control' %>
            </div>
            <div class="form-group mb30">
              <%= f.label :long_desc, class: "control-label" %>
              <%= f.text_area :long_desc, class: 'form-control' %>
            </div>

            <h2 class="title-2">Add Images to Your Ad</h2>
            <div class="form-group">
              <%= f.label :uploads, class: "control-label" %>
              <%= f.file_field :uploads, multiple: true, class: 'file'%>
            </div>
           <%= f.submit "Submit", commit: "Update", class: 'btn btn-common' %>
         <% end %>
       </div>
     </div>
   </div>
 </div>
</section>
<script type="text/javascript">
  $(document).ready(function() {
    $('#brand-select').on('change', function() {
      var select_val = $('#brand-select :selected').val();
      if (select_val == 'new') {
        $('#custom-brand').removeClass('hidden')
        $('#custom-brand').on('change', function() {
          console.log($('#custom-brand').val());
          $('#brand-select :selected').val($('#custom-brand').val());
        });
      }
      else {
        $('#custom-brand').addClass('hidden')
      }
    });
  });
</script>

app/views/products/index.html.erb
<!-- Search wrapper Start -->
<div id="search-row-wrapper">
 <div class="container">
   <div class="search-inner">
       <!-- Start Search box -->
       <div class="row search-bar">
         <div class="advanced-search">
           <%= render :partial => "layouts/search_bar" %>
         </div>
       </div>
       <!-- End Search box -->
   </div>
 </div>
</div>
<!-- Search wrapper End -->

<!-- Main container Start -->
<div class="main-container">
 <div class="container">
   <div class="row">

     <div class="col-sm-3 page-sidebar">
       <aside>
         <div class="inner-box">
           <div class="categories">
             <div class="widget-title">
               <i class="fa fa-align-justify"></i>
               <h4>All Categories</h4>
             </div>
             <div class="categories-list">
               <ul>
                 <% @categories.each do |c| %>
                   <li>
                     <a href="/categories/<%= c.id %>">
                       <i class="<%= @icon_list[c.id-1] %>"></i>
                       <%= c.name.capitalize %>
                       <span class="category-counter">
                         (<%= c.products.count %>)
                       </span>
                     </a>
                   </li>
                 <% end %>
               </ul>
             </div>
           </div>
         </div>
       </aside>
     </div>

     <div class="col-sm-9 page-content">
       <!-- Adds wrapper Start -->

       <% if !@products.nil? %>
         <% if @products.respond_to? :each %>
           <% @products.each.with_index do |product, ind| %>
             <% if product %>
               <div class="adds-wrapper">
                 <div class="item-list">
                   <div class="col-sm-2 no-padding photobox">
                     <div class="add-image">
                       <a href= <%= product_path(product.id) %> >
                         <!-- <img src="images/djembe.jpg" alt=""> -->
                         <% if product.uploads.size > 0 %>
                           <%= image_tag(product.uploads.first) %>
                         <% else %>
                           <%= image_tag("djembe.jpg") %>
                         <% end %>
                       </a>
                     </div>
                   </div>
                   <div class="col-sm-7 add-desc-box">
                     <div class="add-details">
                       <h5 class="add-title">
                         <a href="/products/<%= product.id %>">
                           <%= product.title %>
                         </a>
                       </h5>
                     </div>

                     <div class="item_desc">
                       Description: <%= product.short_desc %><br/>
                     </div>
                   </div>
                 </div>
               </div>
             <% end %>
           <% end %>
         <% end %>
       <% end %>
     </div>
     <!-- Adds wrapper End -->
     <!-- Deleted pagination -->
           <!-- Start Pagination -->
     <div class="pagination-bar">
       <%= paginate @products %>
     </div>
   </div>
 </div>
</div>

app/views/products/new.html.erb
<section id="content">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <div class="box">
          <h2 class="title-2">Share a new product to the community</h2>
          <div class="row search-bar mb30 red-bg">
            <div class="advanced-search">
              <%= form_for @product, class: "search-form" do |f| %>
                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        Category
                      </span>
                      <%= f.collection_select(:categories, @categories, :id, :name, {}, { :multiple => true, class: "dropdown-product selectpicker" }) %>
                    </label>
                  </div>
                </div>

                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        State
                      </span>
                      <%= f.select(:state, @states, {}, { class: "dropdown-product selectpicker" }) %>
                    </label>
                  </div>
                </div>

                <div class="col-md-4 col-sm-12 search-col">
                  <div class="input-group-addon search-category-container">
                    <label class="styled-select">
                      <span class="hidden-sm hidden-xs">
                        Brand
                      </span>
                      <%= f.fields_for :product_detail do |form| %>
                        <select id="brand-select"class="dropdown-product selectpicker" name="product[product_detail][name]">
                          <option value="new" > Ajouter une marque  </option>
                          <% @brands.each do |brand| %>
                            <% if @product.brand_id == brand.id %>
                              <option selected value="<%= brand %>"> <%= brand.name %> </option>
                            <% else %>
                              <option value="<%= brand %>"> <%= brand.name %> </option>
                            <% end %>
                          <% end %>
                        </select>
                      <% end %>
                    </label>
                  </div>
                </div>
              </div>
            </div>

            <div id="brand_field" class="input-icon">
              <input placeholder="Créer une nouvelle marque"type="text" class="form-control input-md" id="custom-brand" />
            </div>

            <div class="form-group mb30">
              <%= f.label :title, class: "control-label" %>
              <%= f.text_field :title, class: 'form-control input-md' %>
            </div>
            <div class="form-group mb30">
              <%= f.label :short_desc, class: "control-label" %>
              <%= f.text_area :short_desc, class: 'form-control' %>
            </div>
            <div class="form-group mb30">
              <%= f.label :long_desc, class: "control-label" %>
              <%= f.text_area :long_desc, class: 'form-control' %>
            </div>

            <h2 class="title-2">Add Images to Your Ad</h2>
            <div class="form-group">
              <%= f.label :uploads, class: "control-label" %>
              <%= f.file_field :uploads, multiple: true, class: 'file'%>
            </div>
           <%= f.submit "Submit", class: 'btn btn-common' %>
         <% end %>
       </div>
     </div>
   </div>
 </div>
</section>
<script type="text/javascript">
  $(document).ready(function() {
    $('#brand-select').on('change', function() {
      var select_val = $('#brand-select :selected').val();
      if (select_val == 'new') {
        $('#custom-brand').removeClass('hidden')
        $('#custom-brand').on('change', function() {
          console.log($('#custom-brand').val());
          $('#brand-select :selected').val($('#custom-brand').val());
        });
      }
      else {
        $('#custom-brand').addClass('hidden')
      }
    });
  });
</script>

app/views/products/show.html.erb
<!-- Start Content -->
<div id="content">
  <div class="container">
    <div class="row">
      <!-- Product Info Start -->
      <div class="product-info">
        <div class="col-sm-8">
          <div class="inner-box ads-details-wrapper">
            <h2> <%= @product.title.capitalize %> </h2>
            <% if @product.inventory.user.id == current_user.id %>
              <h2> <%= link_to "Edit Product", edit_product_path(@product) %> </h2>
            <% else %>
              <div>
                <% if current_user.id != @product.inventory.user.id %>
                  <% if Loan.where(borrower_id: current_user.id, product_id: @product.id).empty? %>
                    <span class="nav-link">
                      <%= form_for @loan, url: "/loans/ask", method: "post", class: "search-form" do |f| %>
                        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                        <%= f.hidden_field :borrower_id, value: current_user.id  %>
                        <%= f.hidden_field :product_id, value: @product.id %>
                        <%= f.hidden_field :owner_id, value: @product.inventory.user.id %>
                        <%= f.submit "Demande de pret", commit: "Create", class: "btn btn-common" %>
                      <% end %>
                    </span>
                  <% end %>
                <% end %>
                <span>
                  Your review
                  <% 5.times do |index| %>
                    <span id="rate-value-<%= index %>" class="fa fa-star"></span>
                  <% end %>
                </span>
              </div>
            <% end %>

            <div class="blockquote-footer"> by: <%= @user.email %>
              <cite title="Source Title">on <%= @product.updated_at %></cite>
            </div>
            <% if !@product.uploads.nil? %>
              <% @product.uploads.each do |u| %>
                <div id="owl-demo" class="owl-carousel owl-theme">
                  <div class="item">
                    <!-- <img src="https://cdn.pixabay.com/photo/2016/06/18/17/42/image-1465348_960_720.jpg" /> -->
                    <%= image_tag u.variant(resize: "250x250") %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <!-- Product Details -->
          <div class="box">
            <h2 class="title-2">
              <strong>Product Details</strong>
            </h2>
            <div class="row">
              <div class="ads-details-info col-md-8">
                <ul class="list-circle">
                  <li>
                    <i class="fa fa-check-circle"></i>
                    <%= @product.long_desc %>
                  </li>
                </ul>
              </div>
              <!-- Details Panel -->
              <div class="col-md-4">
                <aside class="panel panel-body panel-details">
                  <ul>
                    <li>
                      <p class=" no-margin "><strong>Durée du prêt:</strong> de.. à..</p>
                    </li>

                    <li>
                      <p class="no-margin"><strong>Type:</strong> <a href="#">Electronics</a></p>
                    </li>

                    <li>
                      <p class="no-margin"><strong>Location:</strong> 
                        <a href="#">
                          <%= Address.find(@user.address_id).city %>
                        </a>
                      </p>
                    </li>

                    <li>
                      <p class=" no-margin "><strong>Country:</strong> 
                        <%= Address.find(@user.address_id).country %>
                      </p>
                    </li>

                    <% if !@product.brand_id.nil? %>
                      <li>
                        <p class="no-margin"><strong>Brand:</strong> 
                          <a href="#">

                            <%= Brand.find(@product.brand_id).name %>

                          </a>
                        </p>
                      </li>
                    <% end %>
                  </ul>
                </aside>
              </div>
              <div class="ads-action">
                <ul class="list-border">
                  <li>
                    <a href="#">
                      Posted by <i class=" fa fa-user"></i> <%= @user.email %>
                    </a>
                  </li>

                  <li>
                    <a href="#">
                      <i class=" fa fa-heart"></i> Save ad
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="inner-box">
          <div class="widget-title">
            <h4>Advertisement</h4>
          </div>
          <img src="assets/img/img1.jpg" alt="">
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  $(document).ready(function() {
    var is_rated = false
    var stars = $('span[id*=rate-value-]');
    var stars_ids = [];
    stars.each(function() {
      stars_ids.push($(this).attr('id'));
    });
      // On parcourt les étoiles pour savoir sur laquelle le curseur pointe.
      stars.each(function() {
        // On récupère l'étoile courante et les précédentes.
        var current_star = $(this);

        var get_selected_stars = function(stars, stars_ids, current_star) {
          var id = current_star.attr('id').split('-')[2];
          selected_stars = [];
          for (var i = id; i >= 0; i--) {
            if(stars_ids.indexOf('rate-value-'+i) > -1) {
              selected_stars.push(stars[i]);
            }
          }

          return selected_stars;
        }

        var get_unselected_stars = function(stars, stars_ids, current_star) {
          var id = current_star.attr('id').split('-')[2];
          unselected_stars = [];
          for (var i = id; i <= stars.size; i++) {
            if(stars_ids.indexOf('rate-value-'+i) > -1) {
              unselected_stars.push(stars[i]);
            }
          }

          return unselected_stars;
        }
        $(this).on('click', function() {
          is_rated = true;
          data = {
            // authenticity_token: "<%= form_authenticity_token %>",
            rating : get_selected_stars(stars, stars_ids, current_star).length,
            reviewer_id: <%= current_user.id %>,
            reviewed_user_id: <%= @product.inventory.user.id %>,
            comment: "It is a good review !"
          };

          $.ajax({
            type: 'POST',
            url: "/reviews",
            data: data,
            beforeSend: function (xhr) {
              xhr.setRequestHeader("X-CSRF-Token", "<%= form_authenticity_token %>");
            }
          });
        });
        var callback_on = function() {
          
          var self = $(this);  

          selected_stars = get_selected_stars(stars, stars_ids, current_star);
          $(selected_stars).each(function() {
            if(is_rated == false) {
              $(this).addClass('checked');
              $(this).css('color', 'orange');
            }
          });
        }

        var callback_off = function() {
          unselected_stars = get_unselected_stars(stars, stars_ids, current_star);
          $(selected_stars).each(function() {
            if(is_rated == false) {
              $(this).removeClass('checked');
              $(this).css('color', 'rgb(51, 51, 51)');
            }
          });
        };
        $(this).hover(callback_on, callback_off);
      });
    });
</script>