config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  root to: "static_pages#index"
  get '/home', to: "static_pages#home"
	
  resources :trades, :categories, :products, :reviews, :brands
  
  resources :conversations do
    resources :messages
  end

  devise_for :users, :controllers => { registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords" }

  # Messages / Conversations
  get 'messages/index', to: 'messages#index'
  get 'conversations', to: 'conversations#messages/index'

  # Products / Inventory / Search
  get '/my-inventory', to: 'inventories#show'
  get '/products-filtered', to: 'products#index_with_filters'

  post '/products-search', to: 'searches#search'

  # Loans
  post '/loans/ask', to: 'loans#ask'
  get '/loans/ask/cancel/:loan_id', to: 'loans#ask_cancel'
  get '/loans/ask/confirm/:loan_id', to: 'loans#ask_confirm'
  get '/loans/ask/refuse/:loan_id', to: 'loans#ask_refuse'

  get '/loans/back/ask/:loan_id', to: 'loans#back_ask'
  get '/loans/back/confirm/:loan_id', to: 'loans#back_confirm'
  get '/loans/back/refuse/:loan_id', to: 'loans#back_refuse'

  # Profile Info / SMS verification
  get '/profile/account', to: 'profile#account'

  get '/profile/requests-pending', to: 'profile#requests_pending'
  get '/profile/requests-current', to: 'profile#requests_current'
  get '/profile/requests-past', to: 'profile#requests_past'

  get '/profile/asks', to: 'profile#asks'
  get '/profile/asks-pending', to: 'profile#asks_pending'
  get '/profile/asks-current', to: 'profile#asks_current'
  get '/profile/asks-past', to: 'profile#asks_past'

  get '/profile/ask_profile_verification', to: 'profile#ask_profile_verification'
  get '/profile/cancel_profile_verification/:request_id', to: 'profile#cancel_profile_verification'

  post '/profile/verify_profile', to: 'profile#verify_profile'
  get '/profile/close', to: 'profile#close'

  #error views 
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
end

app/models/address.rb
class Address < ApplicationRecord
	has_one :user
	geocoded_by :full_address

	after_validation :geocode

	# after_initialize do |address|
	# 	a = address.geocode
	# 	puts a
 #  end

	def full_address
		["#{self.street}", self.city, self.country].compact.join(', ')
	end
	
	def to_string
		self.street + ', ' + self.postal_code + ' ' + self.city + ', ' + self.country
	end
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :products
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # This scope validation takes the sender_id and recipient_id for the conversation and checks whether a conversation exists between the two ids because we only want two users to have one conversation.

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :products
end

app/models/loan.rb
class Loan < ApplicationRecord
	has_one :product
	has_one :owner, class_name: 'User', foreign_key: 'owner_id', inverse_of: :owns
	has_one :borrower, class_name: 'User', foreign_key: 'borrower_id', inverse_of: :borrows
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :inventory
  has_one :brand
  has_and_belongs_to_many :categories
  has_many :loans
  has_many_attached :uploads

  accepts_nested_attributes_for :brand

  paginates_per 10
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :reviewer, :class_name => 'User', inverse_of: :reviews
	belongs_to :reviewed_user, :class_name => 'User', inverse_of: :notes
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  has_many_attached :images, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable #added to generate email confirmations after creating account

  belongs_to :address
  accepts_nested_attributes_for :address
  
	has_one_attached :header_image
  has_many :trades
  has_many :owns, inverse_of: :owner, :class_name => 'Loans', :foreign_key => 'owner_id'
  has_many :borrows, inverse_of: :borrower, :class_name => 'Loans', :foreign_key => 'borrower_id'
  has_many :reviews, dependent: :destroy, inverse_of: :reviewer, :class_name => 'Review'
  has_many :notes, dependent: :destroy, inverse_of: :reviewed_user, :class_name => 'Review'

  private
    attr_accessor :verification_code
  public
    def get_verification_code
      @verification_code
    end

    def set_verification_code(code)
      @verification_code = code
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer Section Start -->
<footer>
  <!-- Footer Area Start -->
  <section class="footer-Content">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-delay="0">
          <div class="widget">
            <h3 class="block-title">À propos du HOP</h3>
            <div class="textwidget">
              <p>Spectacle, cinéma, musique, travaux d'entretien des espaces verts ou encore réparations d'objets en tout genre, tant de domaines où le matériel fait souvent défaut ! Nous souhaitons développer un espace dans lequel il sera possible de partager du matériel entre particuliers et professionnels.</p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-delay="0.5">
          <div class="widget">
            <h3 class="block-title">Liens utiles</h3>
            <ul class="menu">
                  <% unless user_signed_in? %>
                  <li>
                    <%= link_to "Se connecter", new_user_session_path %>
                  </li>
                  <li>
                    <%= link_to "Créer un compte", new_user_registration_path %>
                  </li>
                  <% else %>
                  <li>
                    <%= link_to "Produits", "/products" %>
                  </li>
                  <li>
                    <%= link_to "Messages", conversations_path %>
                  </li>
                  <li>
                    <%= link_to "Compte", edit_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to "Inventaire", my_inventory_path %>
                  </li>
                  <li>
                    <%= link_to "Demandes", profile_requests_pending_path %>
                  </li>
                  <li>
                    <%= link_to "Emprunts", profile_asks_pending_path %>
                  </li>        
                  <li>
                    <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  </li>
                  <% end %>
            </ul>
          </div>
        </div>

        <!-- Tweets Begin -->
        <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-delay="1s">
          <div class="widget">
            <h3 class="block-title">Derniers tweets</h3>
            <div class="twitter-content clearfix">
              <ul class="twitter-list">
                <!-- BotTwitter Starts -->
                <% BotTwitter.new.stream_tweet.each do |text| %>
                  <li class="clearfix">
                    <span>
                      <%= text %>
                      <a href="https://twitter.com/HOverproduce">http://t.co/cLo2w7rWOx</a>
                    </span>
                  </li>
                <% end %>
                <!-- BotTwitter ends---  -->
                <li class="clearfix">
                  <span>
                  Introducing Bootstrap 4 Features: What’s new, What’s gone!
                  <a href="#">http://t.co/cLo2w7rWOx</a>
                </span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- Tweets End -->

        <div class="col-md-3 col-sm-6 col-xs-12 wow fadeIn" data-wow-delay="1.5s">
          <div class="widget">
            <h3 class="block-title">Publicité</h3>
            <ul class="featured-list">
              <li>
                <!-- <img alt="" src="assets/img/featured/img1.jpg"> -->
                <%= image_tag("featured/img1.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
              <li>
                <!-- <img alt="" src="assets/img/featured/img2.jpg"> -->
                <%= image_tag("featured/img2.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
              <li>
                <!-- <img alt="" src="assets/img/featured/img3.jpg"> -->
                <%= image_tag("featured/img3.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
              <li>
                <!-- <img alt="" src="assets/img/featured/img4.jpg"> -->
                <%= image_tag("featured/img4.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
              <li>
                <!-- <img alt="" src="assets/img/featured/img5.jpg"> -->
                <%= image_tag("featured/img5.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
              <li>
                <!-- <img alt="" src="assets/img/featured/img6.jpg"> -->
                <%= image_tag("featured/img6.jpg") %>
                <div class="hover">
                  <a href="#"><span>$49</span></a>
                </div>
              </li>
            </ul>             
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Footer area End -->
  
  <!-- Copyright Start  -->
  <div id="copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="site-info pull-left">
            <p>All copyrights reserved &copy; 2018 - Designed by <a href="http://graygrids.com" rel="nofollow">GrayGrids</a></p>
          </div>              
          <div class="bottom-social-icons social-icon pull-right">  
            <a class="facebook" target="_blank" href="https://web.facebook.com/GrayGrids"><i class="fa fa-facebook"></i></a> 
            <a class="twitter" target="_blank" href="https://twitter.com/GrayGrids"><i class="fa fa-twitter"></i></a>
            <a class="dribble" target="_blank" href="https://dribbble.com/"><i class="fa fa-dribbble"></i></a>
            <a class="flickr" target="_blank" href="https://www.flickr.com/"><i class="fa fa-flickr"></i></a>
            <a class="youtube" target="_blank" href="https://youtube.com"><i class="fa fa-youtube"></i></a>
            <a class="google-plus" target="_blank" href="https://plus.google.com"><i class="fa fa-google-plus"></i></a>
            <a class="linkedin" target="_blank" href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Copyright End -->
  <!-- Footer Section End --> 
  <!-- Go To Top Link -->
  <a href="#" class="back-to-top">
    <i class="fa fa-angle-up"></i>
  </a>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Header Section Start -->
<div class="header">    
  <nav class="navbar navbar-default main-navigation" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <!-- Stat Toggle Nav Link For Mobiles -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- End Toggle Nav Link For Mobiles -->
        <div class="navbar-brand logo" style="width: 200px; height: 60px" href="index.html">
          <%= link_to image_tag("logo_hop.png"), root_path, id:"colorlib-logo" %>
        </div>
      </div>
      <!-- brand and toggle menu for mobile End -->

          <!-- Navbar Start -->
          <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
              <% unless user_signed_in? %>
                  <li>
                    <%= link_to "Se connecter", new_user_session_path %>
                  </li>
                  <li>
                    <%= link_to "Créer un compte", new_user_registration_path %>
                  </li>
                  <% else %>
                  <li>
                    <%= link_to "Produits", "/products" %>
                  </li>
                  <li>
                    <%= link_to "Messages", conversations_path %>
                  </li>
                  <li>
                    <div class="dropdown-nav">
                    <button class="dropbtn">Profil</button>
                    <ul class="dropdown-content">
                      <li>
                        <%= link_to "Compte", edit_user_registration_path %>
                      </li>
                      <li>
                        <%= link_to "Inventaire", my_inventory_path %>
                      </li>
                      <li>
                        <%= link_to "Demandes", profile_requests_pending_path %>
                      </li>
                      <li>
                        <%= link_to "Emprunts", profile_asks_pending_path %>
                      </li>
                    </ul>
                    </div>        
                  </li>
                  <li>
                    <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  </li>
                  <% end %>
              <li class="postadd">
            <a class="btn btn-danger btn-post" href="/products/new">
              <span class="fa fa-plus-circle"></span>
              Produits
            </a>
          </li>
        </ul>
      </div>
      <!-- Navbar End -->
    </div>
  </nav>

</div>
<!-- Header Section End -->

app/views/layouts/_search_bar.html.erb
<form class="search-form" action="/products-search" method="post" style="position: relative; z-index: 10;">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="col-md-12 col-sm-6 search-col">
    <div class="col-md-3 col-sm-6 search-col">
      <input class="form-control" name="search[location]" type="text" value="" placeholder="Distance maximale (km)" />
    </div>      
    <div class="col-md-3 col-sm-6 search-col">
      <div class="input-group-addon search-category-container">
        <label class="styled-select">
          <select class="dropdown-product selectpicker" multiple="true" name="search[categories][]" style="position: relative; z-index: 10;" >
            <% @categories.each do |c| %>
              <option value="<%= c.id %>"> <%= c.name %> </option>
            <% end %>
          </select>
        </label>
      </div>
    </div>
    <div class="col-md-3 col-sm-6 search-col">
      <input class="form-control keyword" name="search[keyword]" value="" placeholder="Enter Keyword" type="text">
      <i class="fa fa-search"></i>
    </div>
    <div class="col-md-3 col-sm-6 search-col">
      <button type="submit" class="btn btn-common btn-search btn-block" id="btn-search-bar">
        <strong>Search</strong>
      </button>
    </div>
  </div>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HopApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "layouts/navbar" %>
    <%= yield %>
    <%= render :partial => "layouts/footer" %>
  </body>
</html>